apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  namespace: goldengoose
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goldengoose
      track: canary
  template:
    metadata:
      labels:
        app: goldengoose
        track: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: goldengoose
        image: index.docker.io/dippynark/goldengoose
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: 100Mi
        readinessProbe:
          timeoutSeconds: 2
          httpGet:
            path: /
            port: 8000
        livenessProbe:
          timeoutSeconds: 10
          httpGet:
            path: /
            port: 8000